# Workflow name
name: Backend Continuous Deployment
# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  push:
  # Automatic trigger on push events to the main branch
    branches:
      - main
    paths:
      - 'starter/backend/**'

env:
  PYTHON_VERSION: 3.11

jobs:
  LINT:
    name: Backend Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pipenv
          key: pipenv-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            pipenv-${{ runner.os }}-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install pipenv
        run: |
          pip install pipenv && pip install flake8

      - name: Install dependencies
        run: |
          pipenv install

      - name: Run lint
        run: |
          pipenv run lint

  test:
    name: Backend Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install pipenv
        run: |
          pip install pipenv && pip install flake8

      - name: Install dependencies
        run: |
          pipenv install

      - name: Run tests
        run: |
          pipenv run test